require: rubocop-rspec

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.2
  DisplayCopNames: true

  Include:
    - Rakefile
    - Gemfile
    - config.ru
    - lib/**/*

  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'vendor/bundle/**/*'

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/FirstArrayElementLineBreak:
  Enabled: true

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/FirstMethodParameterLineBreak:
  Enabled: true

Layout/MultilineAssignmentLayout:
  Enabled: true

Metrics/BlockLength:
 ExcludedMethods:
   - describe
   - context
   - shared_examples_for

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

# Seems to be breaking tests when recommended fixes for this cop are applied
Rails/HttpPositionalArguments:
  Enabled: false

Rails/InverseOf:
  Enabled: false

RSpec/NestedGroups:
  Max: 7

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/OptionHash:
  Enabled: true

Style/Send:
  Enabled: true

Style/SymbolArray:
  Enabled: true

Style/MixinUsage:
  Exclude:
    - bin/*
