version: '3.4'

services:
  db:
    container_name: db
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-automation-calculator-password}
      - POSTGRES_DB=${POSTGRES_DB:-automation-calculator-development}
    image: postgres:10.1-alpine
    ports:
      - "5434:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
