FROM ruby:2.2.9-slim-jessie

#Install dependencies, starting with nokogiri and it's dependencies
RUN apt-get update
RUN apt-get install -y build-essential patch ruby-dev zlib1g-dev liblzma-dev
RUN gem install nokogiri
RUN gem install bundler

COPY . /usr/src/app
WORKDIR /usr/src/app
RUN bundle install